# Generated by Django 2.0 on 2018-01-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='question choice text description', max_length=512)),
                ('votes', models.IntegerField(default=0, help_text='choice selected times')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='description question', max_length=512)),
                ('pub_date', models.DateTimeField(help_text='question publish date', verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='related to polls_question table', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
